title: Like Tech
email: stylejy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A team tech blog written by JooYoung Lee, Jihoon Na and Seokkyu Ryu.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://stylejy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: JooYoung Lee, Jihoon Na and Seokkyu Ryu # add your name
# Author JooYoung Lee
author-jy: JooYoung Lee
author-pic-jy: jy.jpg
about-author-jy: JooYoung Lee
# Author JiHoon Na
author-jh: JiHoon Na
author-pic-jh: jh.jpg
about-author-jh: JiHoon Na
# Seokkyu Ryu
author-sk: Seokkyu Ryu
author-pic-sk: sk.jpg
about-author-sk: Seokkyu Ryu

# Contact links
email: # Add your Email address
website: liketech.codes # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: stylejy # Add your Github handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: jy-lee # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
